# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a156a70379ab37abae45e4a6d64a2e621aa3f114000e79426db747ea0f9ef671644dd4bac13f37ab4bc5fcb59915ab60068a879da457222396dd5f7fbc2629c

test:
  secret_key_base: 8aa1a4d08b7bc7c5e68babe3ca913fb07a059ec1d2995eda696e86473b75b52f1054eed4e6a6ea07c1eab44a4559b0fefea73e981af82567b2501dab5c8f1a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
